<a href="https://colab.research.google.com/github/RENJITHVS/RNN/blob/main/embedding_simpleRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Embedding

in NLP, word embedding is a term used for the representaion of words for text analysis, typically in the form of real-valued vector that encodes the meaning of the word such that the words that are closer in the vector space are expected to be similar in meaning (semanting meaning).

Eg: word2Vec, Glove

- When we use interger encoding , it has a lot of sparce vectors (most values are zeros), so most values are zeros.

In [1]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [2]:
import numpy as np

input_data = ['go india',
		'india india',
		'hip hip hurray',
		'thu thuru thu thuru thumbi',
    'poda pulle police ninne pinne kandoolam',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'pooomanamee oru raaga meegma thaaa',
		'inquilab Zindabad']

In [3]:
tokenizer.fit_on_texts(input_data)

In [4]:
len(tokenizer.word_index)

27

In [5]:
sequences = tokenizer.texts_to_sequences(input_data)
sequences

[[8, 1],
 [1, 1],
 [2, 2, 9],
 [3, 4, 3, 4, 10],
 [11, 12, 13, 14, 15, 16],
 [17, 18, 19, 20],
 [5, 5],
 [6, 6],
 [7, 7],
 [21, 22, 23, 24, 25],
 [26, 27]]

In [13]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 8,  1,  0,  0,  0,  0],
       [ 1,  1,  0,  0,  0,  0],
       [ 2,  2,  9,  0,  0,  0],
       [ 3,  4,  3,  4, 10,  0],
       [11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20,  0,  0],
       [ 5,  5,  0,  0,  0,  0],
       [ 6,  6,  0,  0,  0,  0],
       [ 7,  7,  0,  0,  0,  0],
       [21, 22, 23, 24, 25,  0],
       [26, 27,  0,  0,  0,  0]], dtype=int32)

In [7]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [15]:
model = Sequential()
model.add(Embedding(27,output_dim=2,input_length=6))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 6, 2)              54        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile('adam','accuracy')
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 55ms/step
[[[-0.04336268 -0.01339508]
  [-0.00740581 -0.01423254]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]]

 [[-0.00740581 -0.01423254]
  [-0.00740581 -0.01423254]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]]

 [[ 0.02237822  0.02650196]
  [ 0.02237822  0.02650196]
  [-0.04004588 -0.01175297]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]
  [ 0.00448662 -0.02506871]]

 [[ 0.02100855 -0.04216139]
  [ 0.04500485  0.01227108]
  [ 0.02100855 -0.04216139]
  [ 0.04500485  0.01227108]
  [-0.00341846  0.0170234 ]
  [ 0.00448662 -0.02506871]]

 [[-0.01418455  0.00674997]
  [ 0.03903138 -0.02556773]
  [-0.04248315  0.04448276]
  [ 0.029027   -0.03768801]
  [-0.03079057 -0.01313074]
  [-0.03582463  0.02015814]]

 [[ 0.0373241   0.02426933]
  [-0.01999663  0.00977255]
  [-0.02445836 -0.01256498]
  [-0.01155027

In [17]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [18]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [19]:
X_train.shape

(25000, 50)

In [22]:
model = Sequential()
model.add(Embedding(10000, 2,input_length= 50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________
